#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from currency_converter_config.ui on Sat Jun 18 12:01:13 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CurrencyConverterConfig(object):
    def setupUi(self, CurrencyConverterConfig):
        CurrencyConverterConfig.setObjectName(_fromUtf8("CurrencyConverterConfig"))
        CurrencyConverterConfig.resize(368, 185)
        CurrencyConverterConfig.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtGui.QVBoxLayout(CurrencyConverterConfig)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_update_interval = QtGui.QLabel(CurrencyConverterConfig)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_update_interval.setFont(font)
        self.label_update_interval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_update_interval.setObjectName(_fromUtf8("label_update_interval"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_update_interval)
        self.update_interval = QtGui.QSpinBox(CurrencyConverterConfig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_interval.sizePolicy().hasHeightForWidth())
        self.update_interval.setSizePolicy(sizePolicy)
        self.update_interval.setMaximumSize(QtCore.QSize(100, 16777215))
        self.update_interval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.update_interval.setMaximum(1440)
        self.update_interval.setSingleStep(10)
        self.update_interval.setObjectName(_fromUtf8("update_interval"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.update_interval)
        self.desc_update_interval = QtGui.QLabel(CurrencyConverterConfig)
        self.desc_update_interval.setWordWrap(True)
        self.desc_update_interval.setObjectName(_fromUtf8("desc_update_interval"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.desc_update_interval)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_update_interval.setBuddy(self.update_interval)
        self.desc_update_interval.setBuddy(self.update_interval)

        self.retranslateUi(CurrencyConverterConfig)
        QtCore.QMetaObject.connectSlotsByName(CurrencyConverterConfig)

    def retranslateUi(self, CurrencyConverterConfig):
        CurrencyConverterConfig.setWindowTitle(kdecore.i18n("Form"))
        self.label_update_interval.setToolTip(kdecore.i18n("Update interval in minutes."))
        self.label_update_interval.setText(kdecore.i18n("Update interval"))
        self.update_interval.setSuffix(kdecore.i18n(" minutes"))
        self.desc_update_interval.setText(kdecore.i18n("If the interval is set to \'0\' no regular updates will take place."))

